package com.iideprived.rain.model.jobs.implementation.jobs

object CronString {
    val EVERY_MINUTE = "* * * * *"
    val EVERY_HOUR = "0 * * * *"
    val EVERY_DAY = "0 0 * * *"
    val EVERY_WEEK = "0 0 * * 0"
    val EVERY_MONTH = "0 0 1 * *"
    val EVERY_YEAR = "0 0 1 1 *"
    val EVERY_30_MINUTES = "*/30 * * * *"
    val EVERY_15_MINUTES = "*/15 * * * *"
    val EVERY_10_MINUTES = "*/10 * * * *"
    val EVERY_5_MINUTES = "*/5 * * * *"
    val EVERY_2_MINUTES = "*/2 * * * *"
    val EVERY_SUNDAY = "0 0 * * 0"
    val EVERY_MONDAY = "0 0 * * 1"
    val EVERY_TUESDAY = "0 0 * * 2"
    val EVERY_WEDNESDAY = "0 0 * * 3"
    val EVERY_THURSDAY = "0 0 * * 4"
    val EVERY_FRIDAY = "0 0 * * 5"
    val EVERY_SATURDAY = "0 0 * * 6"
    val EVERY_WEEKDAY = "0 0 * * 1-5"
    val EVERY_WEEKEND = "0 0 * * 0,6"
    val EVERY_2_HOURS = "0 */2 * * *"
    val EVERY_3_HOURS = "0 */3 * * *"
    val EVERY_4_HOURS = "0 */4 * * *"
    val EVERY_6_HOURS = "0 */6 * * *"
    val EVERY_8_HOURS = "0 */8 * * *"
    val EVERY_12_HOURS = "0 */12 * * *"
    val EVERY_3_DAYS = "0 0 */3 * *"
    val EVERY_5_DAYS = "0 0 */5 * *"
    val EVERY_7_DAYS = "0 0 */7 * *"
    val EVERY_14_DAYS = "0 0 */14 * *"
    val EVERY_SEASON = "0 0 1 3,6,9,12 *"
    val EVERY_QUARTER = "0 0 1 1,4,7,10 *"
    val EVERY_HALF_YEAR = "0 0 1 1,7 *"
}